### ISSUE TITLE
ibc.chain_stats times out bescause default_options in rest.js is modified

### ISSUE THREAD

**Issue by nilnullzip** [IBM-Blockchain/ibm-blockchain-js#10]
The symptom is that the http get called from ibc.prototype.chain_stats times out.

The culprit is mergeBtoA. It copies properties from default_options into the passed options object. That passed object is subsequently modifed to add options.header.content-length property. The problem here is that the header object is actually still the default_options.header object. So the default header is modified and that content length is incorrectly specified for a subsequent get calls that should have no content-length specified.

Commit `c10ac4276228657e4de3f9b1fd4023e368bd9575` tries to fix this bug by deleting the content-length property when body is empty. However this is not a complete fix as other header properties will still be potentially incorrect. The right fix is to modify mergeBtoA:

```
			a[i] = JSON.parse(JSON.stringify(b[i]));
```

This (deep) clones a new object instead of substituting the one from default_options.

Also probably bad practice to modify the passed options object. A similar strategy could be employed to clone it as well.

**Comment by dshuffma-ibm** [comment]
Great tip thanks!  I've added it as of https://github.com/IBM-Blockchain/ibm-blockchain-js/commit/71b6bba5acc37fddc1b3c74d9e9895c81b977256

**Comment by nilnullzip** [comment]
You might also want to delete this one on line 147 of rest.js. With that fix, it's no longer needed. And it might cause confusion in the future. (Simpler is better.)

```
	else if(options.headers['content-length']) delete options.headers['content-length'];			//we don't need you
```
