### ISSUE TITLE
Shadowing blockchain history?

### ISSUE THREAD

**Issue by nilnullzip** [IBM-Blockchain/ibm-blockchain-js#11]
I have a demo application on bluemix blockchain where I need to access state history. I'm not sure blockchain-js has sufficient function to allow that.

The application is a real use case of a county assessor's office. There are owners and there are property titles that can be transferred between owners. When viewing a property title, it is necessary to list the ownership history. I had previously implemented this application using the Open Assets protocol atop the bitcoin blockchain.

I understand the blockchain itself does not support history, so it is necessary to shadow history. I looked at using ibc.monitor_blockheight to trigger on every block a read the blockchain state using chaincode.read. But that doesn't work as the state could have changed multiple times before it is read.

Is there a better way to save or access history as needed for my application? Or is some protocol/API development needed to support that?

**Comment by dshuffma-ibm** [comment]
You are correct in that the current SDK cannot help create an accurate shadow state history. We would need API changes in Hyperledger to complete this task... 

- You could ask them for the ability to read past states + a REST interface.  This would be great for auditability, but its probably performance intensive.
- If you are only interested in your own chaincode state then you could track history in your own chaincode.  This seems messy at first glance, and only works if the chaincode itself is altered which may or may not be of use to you.

I would advise to start this discussion with the [Hyperledger fabric](https://github.com/hyperledger/fabric) team and see if this sort of thing is on their radar.
