### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by joequant** [IBM-Blockchain/ibm-blockchain-js#13]
The code in this tree does not have a license.

**Comment by mastersingh24** [comment]
https://github.com/IBM-Blockchain/ibm-blockchain-js/commit/ac7dcd8b3ee20190a2ca888710e13e5b00f6e7ae closes this.  Added Apache2 license and updated package.json to reflect

**Comment by joequant** [comment]
Thanks!!!!

I've added a issue to "marbles".  Could you add a LICENSE.md file for that
project.
