### ISSUE TITLE
Querying error not handled

### ISSUE THREAD

**Issue by privoal-ak** [IBM-Blockchain/ibm-blockchain-js#16]
When querying a chaincode, the "error" field of the response it not treated as an error.

Example :
`[ibc-js] get_all_clients  - success: { jsonrpc: '2.0',
  error: 
   { code: -32000,
     message: 'Registration missing',
     data: 'User not logged in. Use the \'/registrar\' endpoint to obtain a security token.' },
  id: 1465917260947 }`

When the response is as shown, the specified callback is called with its first parameter as null and the second as undefined (respectively corresponding to error and result).

The problem is, you could not have any information about this error in the scope of the callback function.

**Comment by dshuffma-ibm** [comment]
Thanks for spotting that, updated in https://github.com/IBM-Blockchain/ibm-blockchain-js/commit/6e6195c9bcd23f39e4797ccaa844e205d22486d3
