### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by maruthidonthi** [IBM-Blockchain/ibm-blockchain-js#27]
I am trying to deploy marbles chaincode using ibm-blockchain-js. 

Here is my Code:

```js
// Starting out by requiring all dependancies
var Ibc = require ('ibm-blockchain-js');
 var ibc = new Ibc();
// Then define new instances that will be needed

var chaincode = {};


// configure ibc-js sdk by defining options
var options = {
    network:{
      peers: [{
        "api_host": "xxxxxxxxxxxxxxx",
        "api_port": 444,
        "api_port_tls": 444,
        "id": "xxxxxx",
        "api_url": "http://xxxxxx.us.blockchain.ibm.com:444"
      }],
      users: [{
        "username": "user_type1_0",
        "secret": "xxxxx",
        "enrollId": "user_type1_0",
        "enrollSecret": "xxxxxxx"
      }],
      options:{
        quiet: false,
        timeout: 60000
      }
    },
    chaincode:{
            zip_url: 'https://github.com/ibm-blockchain/marbles-chaincode/archive/master.zip',
            unzip_dir: 'marbles-chaincode-master/part2',
            git_url: 'https://github.com/ibm-blockchain/marbles-chaincode/part2',
            deployed_name: null
        },
  };

// Load the Marbles2 chaincode, with defined options, and return call-back-when-ready function.
ibc.load(options, cb_ready);

// Define the call-back-when-ready function returned above
// call-back-when-ready function has err
function cb_ready(err, cc){
	//response has chaincode functions
  //app1.setup(ibc, cc);
  //app2.setup(ibc, cc);
	// if the deployed name is blank, then chaincode has not been deployed
	if(cc.details.deployed_name === null){
        cc.deploy('init', ['99'], {save_path: './cc_summaries', delay_ms: 60000}, cb_deployed);
  	}
  	else{
  		console.log('chaincode summary file indicates chaincode has been previously deployed');
      cb_deployed();
	}
}
// Step 5 ==================================
    function cb_deployed(err){
        console.log('sdk has deployed code and waited');
        //chaincode.query.read(['a']);
    }
```

When I try to execute I got the deployment error 400. Here is my logs looks like:

[ibc-js] Peer:  864acfab0a734673a4f99844a8b02129-vp0-864acfab0a73...:444
[ibc-js] No membership users found after filtering, assuming this is a network w/o membership
[ibc-js] removing temp dir
[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/marbles-chaincode/zip/master
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'part2_chaincode.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/openblockchain/obc-peer/openchain/chaincode/shim
[ibc-js] Parsing file for invoke functions - part2_chaincode.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - part2_chaincode.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
[ibc-js] Deploy Chaincode - Starting
[ibc-js] 	function: init , arg: [ '99' ]

	 Waiting...
[https POST - z] /devops/deploy
  body: {"type":"GOLANG","chaincodeID":{"path":"https://github.com/ibm-blockchain/marbles-chaincode/part2"},"ctorMsg":{"function":"init","args":["99"]}}
[https POST - z] Status code: 400
[https POST - z] Error - status code: 400 {"Error": "Must supply username for chaincode when security is enabled."}
[ibc-js] deploy - failure: 400

Any Help would be helpful. Thanks in advance.

**Comment by dshuffma-ibm** [comment]
looks like you using a Bluemix network is that correct? 
does your code literally have these x's:
![image](https://cloud.githubusercontent.com/assets/16085295/20071575/fab13364-a4f2-11e6-9f1e-5563cd147f71.png)

you will need to edit that following: [configure the sdk for your blockchain network](https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#configure-the-sdk-for-your-blockchain-network)

**Comment by jeeju** [comment]
1. Yes, I am using bluemix network.
2. I dont have xxxx values, I just replaced my original values with xxx in code snippet above.
 My actual code has:
peers: [{
        "api_host": "864acfab0a734673a4f99844a8b02129-vp0.us.blockchain.ibm.com",
        "api_port": 444,
        "api_port_tls": 444,
        "id": "864acfab0a734673a4f99844a8b02129-vp0",
        "api_url": "http://864acfab0a734673a4f99844a8b02129-vp0.us.blockchain.ibm.com:444"
      }],

**Comment by dshuffma-ibm** [comment]
ha ok had to make sure.

so looking closer at your logs this line is bad:
`[ibc-js] Found shim version: github.com/openblockchain/obc-peer/openchain/chaincode/shim`

nobody should be using obc-peer based shim anymore, its months old.  looking at your `options.chaincode` field is the cause of the problem.  change it to:

```js
chaincode:{
			zip_url: 'https://github.com/ibm-blockchain/marbles/archive/v1.0.zip',
			unzip_dir: 'marbles-1.0/chaincode/part2',		
			git_url: 'http://gopkg.in/ibm-blockchain/marbles.v1/chaincode/part2',	
}					
```

**Comment by jeeju** [comment]
I have made those changes: Now logs looks like:

[ibc-js] Peer:  864acfab0a734673a4f99844a8b02129-vp0-864acfab0a73...:444
[ibc-js] No membership users found after filtering, assuming this is a network w/o membership
[ibc-js] removing temp dir
[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/marbles/zip/v1.0
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'part2_chaincode.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - part2_chaincode.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - part2_chaincode.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
[ibc-js] Deploy Chaincode - Starting
[ibc-js] 	function: init , arg: [ '99' ]


	 Waiting...
[https POST - r] /chaincode
  body: {"jsonrpc":"2.0","method":"deploy","params":{"type":1,"chaincodeID":{"path":"http://gopkg.in/ibm-blockchain/marbles.v1/chaincode/part2"},"ctorMsg":{"function":"init","args":["99"]}},"id":1478546709432}
[https POST - r] Status code: 200


	 deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
  error: 
   { code: -32602,
     message: 'Invalid params',
     data: 'Must supply username for chaincode when security is enabled.' },
  id: 1478546709432 }

**Comment by dshuffma-ibm** [comment]
ok so next problematci log line is: 
```
[ibc-js] No membership users found after filtering, assuming this is a network w/o membership
```

you are likely using ibc v1.2.8 which has a `filter_users()` function that will remove enroll Ids from your mycreds.json file that do not contain `type1` in their name. this function was removed in v1.3.0, you could upgrade to ibc v1.3.0 and see if that gets you further... but i'm concerned as to why it didn't find any `type1` enrollIds in your list.

double check your `options.network.users` array.

**Comment by jeeju** [comment]
I have upgraded to the 1.3.0 version but having the same issue.
I have the valis users values, I can deploy the same chaincode with these user credentials through blockchain UI, But not using nodejs sdk.

logs now looks like:
ibc-js] Peer:  864acfab0a734673a4f99844a8b02129-vp0-864acfab0a73...:444
[ibc-js] No membership users found, assuming this is a network w/o membership
[ibc-js] removing temp dir
[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/marbles/zip/v1.0
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'part2_chaincode.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - part2_chaincode.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - part2_chaincode.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
[ibc-js] Deploy Chaincode - Starting
[ibc-js] 	function: init , arg: [ '99' ]


	 Waiting...
[https POST - b] /chaincode
  body: {"jsonrpc":"2.0","method":"deploy","params":{"type":1,"chaincodeID":{"path":"http://gopkg.in/ibm-blockchain/marbles.v1/chaincode/part2"},"ctorMsg":{"function":"init","args":["99"]}},"id":1478548790829}
[https POST - b] Status code: 200


	 deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
  error: 
   { code: -32602,
     message: 'Invalid params',
     data: 'Must supply username for chaincode when security is enabled.' },
  id: 1478548790829 }

**Comment by maruthidonthi** [comment]
any update?

**Comment by maruthidonthi** [comment]
I don't know the reason but, I have changed my user to credentials to user_type1_1. Then run the deploy code and looks like it is working fine.
Example app listening at localhost:8081
info: [ibc-js] Peer:  864acfab0a734673a4f99844a8b02129-vp0-864acfab0a73...:444
info: [ibc-js] Registering  864acfab0a734673a4f99844a8b02129-vp0-864acfab0a73...:444  w/enrollId - user_type1_1
info: [ibc-js] Registration success x1 : user_type1_1
info: [ibc-js] removing temp dir
info: [ibc-js] Downloading zip
info: redirect... https://codeload.github.com/maruthidonthi/AssetTransfer/zip/master
info: [ibc-js] Downloading zip
info: [ibc-js] Unzipping zip
info: [ibc-js] Unzip done
info: [ibc-js] Scanning files 0=README.md, 1=chaincode.go
info: [ibc-js] Parsing file for shim version
info: [ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
info: [ibc-js] Parsing file for invoke functions - chaincode.go
info: [ibc-js] Parsing file for query functions - chaincode.go
warn: ! [ibc-js] Warning - did not find any invoke functions in chaincode's "Invoke()", building a generic "invoke"
info: [ibc-js] Found cc invoke function:  invoke
warn: ! [ibc-js] Warning - did not find any query functions in chaincode's "Query()", building a generic "query"
info: [ibc-js] Found cc query function:  query
info: [ibc-js] load_chaincode() finished
info: [ibc-js] Deploy Chaincode - Starting
info: [ibc-js] 	function: Init , arg: 0=80
info: 

	 Waiting...
info: 

	 deploy success [waiting another 45 seconds]
info: 	 c43f457b07c5ac1e91df98b6b794f6d67310c839d884b28d6b4a646b712678348e1e70150a92804d0843da93b322e87ce93fc1326e26ab2dbd1783361b4b4afd 

info: [ibc-js] Deploy Chaincode - Complete
