### ISSUE TITLE
HFC link in the main README.md is broken

### ISSUE THREAD

**Issue by rturk** [IBM-Blockchain/ibm-blockchain-js#30]
HFC link is broken
here:
https://github.com/IBM-Blockchain/ibm-blockchain-js/blob/master/README.md#ibm-blockchain-js

**Comment by dshuffma-ibm** [comment]
thanks, those guys are always moving things on me =P

fixed in https://github.com/IBM-Blockchain/ibm-blockchain-js/commit/84dd872b788eeb9c68cbf74aac0cb1d7fc8e6957
