### ISSUE TITLE
Where and how do I implement the Usage Steps?

### ISSUE THREAD

**Issue by suffiasameera** [IBM-Blockchain/ibm-blockchain-js#35]
Please explain. I'm unable to follow them.

Thanks!

**Comment by suffiasameera** [comment]
These are my blockchain credentials:


{
  "ibm-blockchain-5-prod": [
    {
      "credentials": {
        "peers": [
          {
            "discovery_host": "9f1fb36b277048779501b1a7a1cfda94-vp1.us.blockchain.ibm.com",
            "discovery_port": 30004,
            "api_host": "9f1fb36b277048779501b1a7a1cfda94-vp1.us.blockchain.ibm.com",
            "api_port_tls": 5004,
            "api_port": 5004,
            "event_host": "9f1fb36b277048779501b1a7a1cfda94-vp1.us.blockchain.ibm.com",
            "event_port": 31004,
            "type": "peer",
            "network_id": "9f1fb36b277048779501b1a7a1cfda94",
            "container_id": "2f0fbf0ff30c12052e8c967ea072434cf3a118158129bb4606e4e771433f6d74",
            "id": "9f1fb36b277048779501b1a7a1cfda94-vp1",
            "api_url": "http://9f1fb36b277048779501b1a7a1cfda94-vp1.us.blockchain.ibm.com:5004"
          },
          {
            "discovery_host": "9f1fb36b277048779501b1a7a1cfda94-vp2.us.blockchain.ibm.com",
            "discovery_port": 30004,
            "api_host": "9f1fb36b277048779501b1a7a1cfda94-vp2.us.blockchain.ibm.com",
            "api_port_tls": 5004,
            "api_port": 5004,
            "event_host": "9f1fb36b277048779501b1a7a1cfda94-vp2.us.blockchain.ibm.com",
            "event_port": 31004,
            "type": "peer",
            "network_id": "9f1fb36b277048779501b1a7a1cfda94",
            "container_id": "2f252d624107917460cec7e2050c1872da35944ac42a050f2bfe421121696874",
            "id": "9f1fb36b277048779501b1a7a1cfda94-vp2",
            "api_url": "http://9f1fb36b277048779501b1a7a1cfda94-vp2.us.blockchain.ibm.com:5004"
          },
          {
            "discovery_host": "9f1fb36b277048779501b1a7a1cfda94-vp0.us.blockchain.ibm.com",
            "discovery_port": 30004,
            "api_host": "9f1fb36b277048779501b1a7a1cfda94-vp0.us.blockchain.ibm.com",
            "api_port_tls": 5004,
            "api_port": 5004,
            "event_host": "9f1fb36b277048779501b1a7a1cfda94-vp0.us.blockchain.ibm.com",
            "event_port": 31004,
            "type": "peer",
            "network_id": "9f1fb36b277048779501b1a7a1cfda94",
            "container_id": "98f85e4c4ec1d128115c1bcf23be7a73e5d4510bc75ba6191c6be0c9f0538423",
            "id": "9f1fb36b277048779501b1a7a1cfda94-vp0",
            "api_url": "http://9f1fb36b277048779501b1a7a1cfda94-vp0.us.blockchain.ibm.com:5004"
          },
          {
            "discovery_host": "9f1fb36b277048779501b1a7a1cfda94-vp3.us.blockchain.ibm.com",
            "discovery_port": 30004,
            "api_host": "9f1fb36b277048779501b1a7a1cfda94-vp3.us.blockchain.ibm.com",
            "api_port_tls": 5004,
            "api_port": 5004,
            "event_host": "9f1fb36b277048779501b1a7a1cfda94-vp3.us.blockchain.ibm.com",
            "event_port": 31004,
            "type": "peer",
            "network_id": "9f1fb36b277048779501b1a7a1cfda94",
            "container_id": "da3ec95d54bdd55c855bfe7c7fe1cc5b94bc4b9258f66140b38a9bd4687f0b0d",
            "id": "9f1fb36b277048779501b1a7a1cfda94-vp3",
            "api_url": "http://9f1fb36b277048779501b1a7a1cfda94-vp3.us.blockchain.ibm.com:5004"
          }
        ],
        "ca": {
          "9f1fb36b277048779501b1a7a1cfda94-ca": {
            "url": "9f1fb36b277048779501b1a7a1cfda94-ca.us.blockchain.ibm.com:30004",
            "discovery_host": "9f1fb36b277048779501b1a7a1cfda94-ca.us.blockchain.ibm.com",
            "discovery_port": 30004,
            "api_host": "9f1fb36b277048779501b1a7a1cfda94-ca.us.blockchain.ibm.com",
            "api_port_tls": 30004,
            "api_port": 30004,
            "type": "ca",
            "network_id": "9f1fb36b277048779501b1a7a1cfda94",
            "container_id": "131970e0dcd8f532fd0072aeb0eeba2ac0733d7571984c719163d71d68b6566f"
          }
        },
        "users": [
          {
            "enrollId": "admin",
            "enrollSecret": "675122e46f",
            "affiliation": "group1",
            "username": "admin",
            "secret": "675122e46f"
          },
          {
            "enrollId": "WebAppAdmin",
            "enrollSecret": "560b973c9e",
            "affiliation": "group1",
            "username": "WebAppAdmin",
            "secret": "560b973c9e"
          },
          {
            "enrollId": "user_type1_0",
            "enrollSecret": "84d49b22cf",
            "affiliation": "group1",
            "username": "user_type1_0",
            "secret": "84d49b22cf"
          },
          {
            "enrollId": "user_type1_1",
            "enrollSecret": "aeccd8c934",
            "affiliation": "group1",
            "username": "user_type1_1",
            "secret": "aeccd8c934"
          },
          {
            "enrollId": "user_type1_2",
            "enrollSecret": "d24e1918a7",
            "affiliation": "group1",
            "username": "user_type1_2",
            "secret": "d24e1918a7"
          },
          {
            "enrollId": "user_type1_3",
            "enrollSecret": "50ca8513c1",
            "affiliation": "group1",
            "username": "user_type1_3",
            "secret": "50ca8513c1"
          },
          {
            "enrollId": "user_type1_4",
            "enrollSecret": "c08d62d029",
            "affiliation": "group1",
            "username": "user_type1_4",
            "secret": "c08d62d029"
          },
          {
            "enrollId": "user_type2_0",
            "enrollSecret": "52c5822224",
            "affiliation": "group1",
            "username": "user_type2_0",
            "secret": "52c5822224"
          },
          {
            "enrollId": "user_type2_1",
            "enrollSecret": "901ece02c7",
            "affiliation": "group1",
            "username": "user_type2_1",
            "secret": "901ece02c7"
          },
          {
            "enrollId": "user_type2_2",
            "enrollSecret": "b6704c5962",
            "affiliation": "group1",
            "username": "user_type2_2",
            "secret": "b6704c5962"
          },
          {
            "enrollId": "user_type2_3",
            "enrollSecret": "098b1273ff",
            "affiliation": "group1",
            "username": "user_type2_3",
            "secret": "098b1273ff"
          },
          {
            "enrollId": "user_type2_4",
            "enrollSecret": "5e31d48415",
            "affiliation": "group1",
            "username": "user_type2_4",
            "secret": "5e31d48415"
          },
          {
            "enrollId": "user_type4_0",
            "enrollSecret": "aab6e9b04e",
            "affiliation": "group1",
            "username": "user_type4_0",
            "secret": "aab6e9b04e"
          },
          {
            "enrollId": "user_type4_1",
            "enrollSecret": "11036f3bbe",
            "affiliation": "group1",
            "username": "user_type4_1",
            "secret": "11036f3bbe"
          },
          {
            "enrollId": "user_type4_2",
            "enrollSecret": "3dd41df7e8",
            "affiliation": "group1",
            "username": "user_type4_2",
            "secret": "3dd41df7e8"
          },
          {
            "enrollId": "user_type4_3",
            "enrollSecret": "fc898cec88",
            "affiliation": "group1",
            "username": "user_type4_3",
            "secret": "fc898cec88"
          },
          {
            "enrollId": "user_type4_4",
            "enrollSecret": "afd6869bcb",
            "affiliation": "group1",
            "username": "user_type4_4",
            "secret": "afd6869bcb"
          },
          {
            "enrollId": "user_type8_0",
            "enrollSecret": "ee4c9c343f",
            "affiliation": "group1",
            "username": "user_type8_0",
            "secret": "ee4c9c343f"
          },
          {
            "enrollId": "user_type8_1",
            "enrollSecret": "5f88d1f173",
            "affiliation": "group1",
            "username": "user_type8_1",
            "secret": "5f88d1f173"
          },
          {
            "enrollId": "user_type8_2",
            "enrollSecret": "e1eda9505f",
            "affiliation": "group1",
            "username": "user_type8_2",
            "secret": "e1eda9505f"
          },
          {
            "enrollId": "user_type8_3",
            "enrollSecret": "03327130da",
            "affiliation": "group1",
            "username": "user_type8_3",
            "secret": "03327130da"
          },
          {
            "enrollId": "user_type8_4",
            "enrollSecret": "d1ea1e694b",
            "affiliation": "group1",
            "username": "user_type8_4",
            "secret": "d1ea1e694b"
          }
        ],
        "cert": "https://blockchain-certs.mybluemix.net/us.blockchain.ibm.com.cert",
        "cert_path": "/certs/peer/cert.pem"
      },
      "syslog_drain_url": null,
      "label": "ibm-blockchain-5-prod",
      "provider": null,
      "plan": "ibm-blockchain-plan-5-prod",
      "name": "Blockchain-fv",
      "tags": [
        "app_services",
        "ibm_created"
      ]
    }
  ]
}

--------------------------------------------------------------------------------------------------------------

Please explain where it needs to be incorporated along with the other steps.

**Comment by mrshah-at-ibm** [comment]
Can you please explain what are you trying to accomplish?

**Comment by dshuffma-ibm** [comment]
note that this SDK is deprecated, you should move on to [HFC](https://www.npmjs.com/package/hfc).

i'm not sure what issues you are seeing. You will need to post code and errors for us to help. the steps to use the SDK are outline in the [readme](https://github.com/IBM-Blockchain/ibm-blockchain-js/blob/master/README.md) under **Usage Steps**. 

its best to reference the marbles examples I linked to you on your other issues.

**Comment by suffiasameera** [comment]
@mrshah-at-ibm I'm using a python code to invoke my blockchain. The invocation happens without the use of HFC. Can you please guide me as to how I should go about it?

**Comment by suffiasameera** [comment]
What are the credentials I'm supposed to be using along with the steps. Please let me know about this!

**Comment by dshuffma-ibm** [comment]
This repo is a Node.js module. I don't know of any python SDKs for Hyperledger Fabric v0.6.... You may want to switch your project to node if you want to use whats already been built, Otherwise you will be going it alone.  If you are comfortable building HTTP request in python then you can follow the [spec](https://github.com/hyperledger/fabric/blob/v0.6/docs/source/protocol-spec.rst#L3919) yourself.

If you choose to build it in node, then I highly recommend you follow the [Marbles v2](https://github.com/IBM-Blockchain/marbles/blob/v2.0/docs/tutorial_part1.md) demo completely. It goes over all your concerns if you don't skip anything.

**Comment by suffiasameera** [comment]
@dshuffma-ibm Can you please tell me how I should be using the HTTP request
in my Python code to invoke the blockchain?
Thanks!

**Comment by dshuffma-ibm** [comment]
Afraid not, there is only limited support here.  Even if you switch to node.js we can only help so much with the older v0.6 Fabric.  We have no bandwidth to help you write code for a new language on the older Fabric version!
