### ISSUE TITLE
The wait time after deploy should be configurable

### ISSUE THREAD

**Issue by mrshah-at-ibm** [IBM-Blockchain/ibm-blockchain-js#7]
The timeout at https://github.com/IBM-Blockchain/ibm-blockchain-js/blob/master/index.js#L699 should be configurable. Can be passed as a parameter.

**Comment by dshuffma-ibm** [comment]
Done in https://github.com/IBM-Blockchain/ibm-blockchain-js/commit/e28eeccffec361611c7eaa24ec44a4ceefbff1f8
